# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scraping.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scraping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0escraping.proto\x12\x08scraping\"U\n\rScrapeRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08gov_name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x13\n\x0bsuffix_link\x18\x04 \x01(\t\"Y\n\x08NewsItem\x12\x10\n\x08gov_name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0c\n\x04link\x18\x05 \x01(\t\"C\n\x0eScrapeResponse\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.scraping.NewsItem\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t2N\n\x0eGovNewsScraper\x12<\n\x07GetNews\x12\x17.scraping.ScrapeRequest\x1a\x18.scraping.ScrapeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scraping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRAPEREQUEST']._serialized_start=28
  _globals['_SCRAPEREQUEST']._serialized_end=113
  _globals['_NEWSITEM']._serialized_start=115
  _globals['_NEWSITEM']._serialized_end=204
  _globals['_SCRAPERESPONSE']._serialized_start=206
  _globals['_SCRAPERESPONSE']._serialized_end=273
  _globals['_GOVNEWSSCRAPER']._serialized_start=275
  _globals['_GOVNEWSSCRAPER']._serialized_end=353
# @@protoc_insertion_point(module_scope)
